// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task_Management.Data;

#nullable disable

namespace Task_Management.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20260927184913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task_Management.Models.ArchivedTask", b =>
                {
                    b.Property<int>("IdArchivedTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArchivedTask"));

                    b.Property<DateOnly>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<int>("CurrentTasktask_id")
                        .HasColumnType("integer");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdArchivedTask");

                    b.HasIndex("CurrentTasktask_id");

                    b.ToTable("ArchivedTasks");
                });

            modelBuilder.Entity("Task_Management.Models.CurrentTask", b =>
                {
                    b.Property<int>("task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("task_id"));

                    b.Property<int?>("assigned_user_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("dateadded")
                        .HasColumnType("date");

                    b.Property<DateOnly>("deadlinedate")
                        .HasColumnType("date");

                    b.Property<bool>("iscompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("priorityid")
                        .HasColumnType("integer");

                    b.Property<int?>("project_id")
                        .HasColumnType("integer");

                    b.Property<int>("statusid")
                        .HasColumnType("integer");

                    b.Property<string>("task_description")
                        .HasColumnType("text");

                    b.Property<string>("task_name")
                        .HasColumnType("text");

                    b.HasKey("task_id");

                    b.HasIndex("priorityid");

                    b.HasIndex("statusid");

                    b.HasIndex("task_name")
                        .IsUnique();

                    b.ToTable("CurrentTasks");
                });

            modelBuilder.Entity("Task_Management.Models.StatusTask", b =>
                {
                    b.Property<int>("IdTaskStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTaskStatus"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTaskStatus");

                    b.ToTable("TaskStatuses");
                });

            modelBuilder.Entity("Task_Management.Models.TaskPriority", b =>
                {
                    b.Property<int>("IdPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPriority"));

                    b.Property<string>("PriorityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPriority");

                    b.ToTable("TaskPriorities");
                });

            modelBuilder.Entity("Task_Management.Models.ArchivedTask", b =>
                {
                    b.HasOne("Task_Management.Models.CurrentTask", "CurrentTask")
                        .WithMany()
                        .HasForeignKey("CurrentTasktask_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("Task_Management.Models.CurrentTask", b =>
                {
                    b.HasOne("Task_Management.Models.TaskPriority", "TaskPriority")
                        .WithMany("CurrentTasks")
                        .HasForeignKey("priorityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_Management.Models.StatusTask", "StatusTask")
                        .WithMany("CurrentTasks")
                        .HasForeignKey("statusid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusTask");

                    b.Navigation("TaskPriority");
                });

            modelBuilder.Entity("Task_Management.Models.StatusTask", b =>
                {
                    b.Navigation("CurrentTasks");
                });

            modelBuilder.Entity("Task_Management.Models.TaskPriority", b =>
                {
                    b.Navigation("CurrentTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
